# Generated by Django 4.2.16 on 2024-10-20 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("last_contact", models.DateField(blank=True, null=True)),
                ("work", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "instagram_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("friend", "Friend"),
                            ("professional", "Professional"),
                            ("doctor", "Doctor"),
                            ("lawyer", "Lawyer"),
                            ("relative", "Relative"),
                            ("schoolmate", "Schoolmate"),
                            ("love_interest", "Love Interest"),
                        ],
                        default="friend",
                        max_length=50,
                    ),
                ),
                (
                    "uploaded_document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "custom_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="circle.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="circle.profile"
                    ),
                ),
            ],
        ),
    ]
